import * as console from "node:console";
import { existsSync, mkdirSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { cwd as processCwd } from "node:process";

import { logHint, logInfo, logNewLine, logStep, logSuccess, logWarning } from "@todti/allure-kit-core";
import { detectPackageManager } from "@todti/allure-kit-npm";
import { Command, Option } from "clipanion";
import prompts from "prompts";

import { getInstallCommand, getTestCommand } from "./ciShared.js";

const CI_FILE = ".gitlab-ci.yml";
const JOB_FILE = join(".gitlab", "allure-report.gitlab-ci.yml");
const JOB_FILE_POSIX = JOB_FILE.split("\\").join("/");
const INCLUDE = `include:\n  - local: ${JOB_FILE_POSIX}\n`;

const buildJobYaml = (params: { image: string; installCommand: string; testCommand: string; configArg: string }) =>
  `# Generated by allure-kit. The job name must stay stable: "allure gitlab" restores
# history.jsonl from the previous run of the same job. Set a masked GITLAB_TOKEN CI/CD
# variable (api scope) to enable history restore and merge request summary comments.
allure-report:
  image: ${params.image}
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - ${params.installCommand}
    - ${params.testCommand} || TESTS_FAILED=1
    - npx allure gitlab ./allure-results${params.configArg} --output allure-report --history-path history.jsonl
    - test -z "$TESTS_FAILED"
  artifacts:
    when: always
    expire_in: 30 days
    expose_as: Allure Report
    paths:
      - allure-report/
      - history.jsonl
`;

export class KitGitlabInitCommand extends Command {
  static paths = [["gitlab", "init"]];

  static usage = Command.Usage({
    description: "Initialize GitLab CI for Allure reports",
    details:
      'Creates a GitLab CI job that runs your tests and calls "allure gitlab" to build the report, restore history, and comment on merge requests. The job lives in .gitlab/allure-report.gitlab-ci.yml and is included from .gitlab-ci.yml.',
    examples: [
      ["gitlab init", "Interactive setup"],
      ["gitlab init --yes", "Create the job without prompts"],
      ["gitlab init --image node:22 --config ./allurerc.mjs", "Custom image and Allure config"],
    ],
  });

  yes = Option.Boolean("--yes,-y", false, { description: "Accept all defaults without prompts" });

  cwd = Option.String("--cwd", { description: "Working directory (default: current directory)" });

  image = Option.String("--image", { description: "Docker image for the job (default: node:20)" });

  allureConfig = Option.String("--config", { description: "Path to Allure config file to use in CI (optional)" });

  testCommand = Option.String("--test-command", {
    description: "Test command to run in CI (default: inferred from package manager)",
  });

  async execute() {
    const str = (value: unknown) => (typeof value === "string" ? value : undefined);
    const workingDir = str(this.cwd) ?? processCwd();
    const jobPath = resolve(workingDir, JOB_FILE);
    const ciPath = resolve(workingDir, CI_FILE);

    console.log("\n  Allure GitLab CI Setup\n");

    const packageManager = await detectPackageManager(workingDir);
    let testCommand = str(this.testCommand) ?? getTestCommand(packageManager);

    if (existsSync(jobPath)) {
      logWarning(`Job file already exists: ${JOB_FILE}`);

      if (this.yes !== true) {
        const { shouldOverwrite } = await prompts({
          type: "confirm",
          name: "shouldOverwrite",
          message: "Overwrite existing job file?",
          initial: false,
        });

        if (!shouldOverwrite) {
          logInfo("Setup cancelled.");
          return;
        }
      }
    }

    if (this.yes !== true) {
      const response = await prompts({
        type: "text",
        name: "testCommand",
        message: "Test command (must produce allure-results)",
        initial: testCommand,
      });

      testCommand = (response.testCommand as string | undefined) ?? testCommand;
    }

    mkdirSync(resolve(workingDir, ".gitlab"), { recursive: true });
    await writeFile(
      jobPath,
      buildJobYaml({
        image: str(this.image) ?? "node:20",
        installCommand: getInstallCommand(packageManager),
        testCommand,
        configArg: str(this.allureConfig) ? ` --config ${str(this.allureConfig)}` : "",
      }),
      "utf-8",
    );
    logSuccess(`Created ${JOB_FILE}`);

    if (!existsSync(ciPath)) {
      await writeFile(ciPath, INCLUDE, "utf-8");
      logSuccess(`Created ${CI_FILE}`);
    } else if (!(await readFile(ciPath, "utf-8")).includes(JOB_FILE_POSIX)) {
      logWarning(`${CI_FILE} already exists and was not modified.`);
      logHint(`Add this to it:\n${INCLUDE}`);
    }

    logNewLine();
    logStep("Next steps:");
    logHint('Add a masked CI/CD variable "GITLAB_TOKEN" (api scope) for history restore and MR comments');
    logHint("Commit and push; the report is exposed as the job artifact \"Allure Report\"");
  }
}
