import type { EcosystemAdapter } from "@todti/allure-kit-core";

import { detectPythonFrameworks } from "./detect-python-frameworks.js";
import {
  appendToRequirementsTxt,
  detectPythonPackageManager,
  getInstallCommand,
  getRemoveCommand,
  type PythonPackageManager,
} from "./detect-python-package-manager.js";
import { PYTHON_FRAMEWORK_REGISTRY } from "./registry.js";

export const pythonAdapter: EcosystemAdapter<PythonPackageManager> = {
  id: "pip",
  displayName: "Python",
  langAliases: ["python", "py"],
  frameworkRegistry: PYTHON_FRAMEWORK_REGISTRY,
  manifestFiles: ["pyproject.toml", "requirements.txt", "requirements-dev.txt", "Pipfile", "setup.py", "setup.cfg"],
  detectPackageManager: detectPythonPackageManager,
  detectFrameworks: detectPythonFrameworks,
  getInstallCommand,
  getRemoveCommand,
  // Unlike npm, Allure 3's report engine (the "allure" CLI) is Node-only and
  // is never auto-installed into a pure Python project — see postInstallHint.
  alwaysInstallPackages: [],
  afterInstall: async (cwd, packageManager, packages) => {
    if (packageManager === "pip") {
      await appendToRequirementsTxt(cwd, packages);
    }
  },
  postInstallHint:
    'Allure reports are generated by the Node.js-based Allure CLI. Run "npx allure generate" (requires Node.js) once your tests produce results.',
};
